---
services:
    grocy:
        image: lscr.io/linuxserver/grocy:latest
        container_name: grocy
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
        volumes:
            - /home/lbouch/apps/grocy/config:/config
        ports:
            - 9283:80
        restart: unless-stopped
