version: '3'

services:
    otrecorder:
        image: owntracks/recorder
        ports:
            - 8083:8083
        volumes:
            - /home/lbouch/apps/owntracks-recorder/config:/config
            - /home/lbouch/apps/owntracks-recorder/store:/store
        restart: unless-stopped
        environment:
            'OTR_HOST': 'bumble-bee.lukebouch.com'
            'OTR_USER': 'internal'
            'OTR_PASS': 'yiS4Rl4LVDY98Te67J9cBcqa4oZLgZ6g'
    owntracks-frontend:
        image: owntracks/frontend
        ports:
            - 8183:80
        environment:
            - SERVER_HOST=otrecorder
            - SERVER_PORT=8083
        restart: unless-stopped
