version: '3'

services:
    otrecorder:
        image: owntracks/recorder
        ports:
            - 8083:8083
        volumes:
            - /home/lbouch/apps/owntracks-recorder/store:/store
        restart: unless-stopped
        env_file:
            - .env
    owntracks-frontend:
        image: owntracks/frontend
        ports:
            - 8183:80
        environment:
            - SERVER_HOST=otrecorder
            - SERVER_PORT=8083
        restart: unless-stopped
