mqtt:
  enabled: true
  host: localhost
  port: 1883

birdseye:
  enabled: true
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  enabled: false

cameras:
  driveway:
    enabled: true
    detect:
      enabled: true
      width: 640
      height: 480
    ffmpeg:
      inputs:
      - path: rtsp://admin:abc12345678@192.168.88.61:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
      - path: rtsp://admin:abc12345678@192.168.88.61:554/cam/realmonitor?channel=1&subtype=1
        roles:
        - detect
    motion:
      mask:
      - 435,0,640,0,640,54,434,52
  driveway_2:
    enabled: true
    detect:
      enabled: true
      width: 640
      height: 480
    ffmpeg:
      inputs:
      - path: rtsp://admin:abc12345678@192.168.88.63:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
      - path: rtsp://admin:abc12345678@192.168.88.63:554/cam/realmonitor?channel=1&subtype=1
        roles:
        - detect
    motion:
      mask:
      - 435,0,640,0,640,54,434,52
  front_yard:
    enabled: true
    detect:
      enabled: true
      width: 640
      height: 480
    ffmpeg:
      inputs:
      - path: rtsp://admin:abc12345678@192.168.88.62:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
      - path: rtsp://admin:abc12345678@192.168.88.62:554/cam/realmonitor?channel=1&subtype=1
        roles:
        - detect
    motion:
      mask:
      - 435,0,640,0,640,54,434,52
