mqtt:
  enabled: False

birdseye:
  enabled: True
  mode: continuous

detect:
  enabled: false

cameras:
  driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:abc12345678@192.168.88.61:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - detect
  driveway_2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:abc12345678@192.168.88.63:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - detect
  front_yard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:abc12345678@192.168.88.62:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - detect
