mqtt:
  enabled: False

birdseye:
  enabled: True
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  enabled: false

record:
  enabled: True
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 30
      mode: motion

cameras:
  driveway:
    enabled: true
    detect:
      enabled: true
      width: 640
      height: 480
    ffmpeg:
      inputs:
        - path: rtsp://admin:abc12345678@192.168.88.61:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:abc12345678@192.168.88.61:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
  driveway_2:
    enabled: true
    detect:
      enabled: true
      width: 640
      height: 480
    ffmpeg:
      inputs:
        - path: rtsp://admin:abc12345678@192.168.88.63:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:abc12345678@192.168.88.63:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
  front_yard:
    enabled: true
    detect:
      enabled: true
      width: 640
      height: 480
    ffmpeg:
      inputs:
        - path: rtsp://admin:abc12345678@192.168.88.62:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:abc12345678@192.168.88.62:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
