version: '3'
services:
    navidrome:
        image: deluan/navidrome:latest
        ports:
            - '4533:4533'
        restart: unless-stopped
        environment:
            # Optional: put your config options customization here. Examples:
            ND_SCANSCHEDULE: 1h
            ND_LOGLEVEL: info
            ND_SESSIONTIMEOUT: 24h
            ND_BASEURL: ''
            ND_UILOGINBACKGROUNDURL: 'https://static.lukebouch.com/posts/boys-camping-trip-2023/carter-cooking-at-the-campsite.jpg'
        volumes:
            - '/home/lbouch/apps/navidrome:/data'
            - '/home/lbouch/music:/music:ro'
