version: "3.2"
services:
  backrest:
    image: garethgeorge/backrest
    container_name: backrest
    hostname: backrest #Use this to set the hostname instead of container ID to the config.json and WebUI.
    volumes:
      - /home/lbouch/apps/backrest/backrest/data:/data
      - /home/lbouch/apps/backrest/config:/config
      - /home/lbouch/apps/backrest/cache:/cache
      - /home/lbouch/apps:/userdata/apps
      - /home/lbouch/music:/userdata/music
      - /media/data/backups/restic:/repos
    environment:
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
    restart: unless-stopped
    ports:
      - 9898:9898
